language: python

services:
  - docker

script: echo "Not implemented"

after_success:
  - pip install awscli
  - export PATH=$PATH:$HOME/.local/bin
  - eval $(aws ecr get-login --region eu-central-1 --no-include-email)
  - docker build . -t tg-alko
  - docker tag tg-alko:latest $AWS_ECR_URL:latest
  - docker push $AWS_ECR_URL:latest
