language: nodejs


script: echo "Not implemented"

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_KEY_ID
  secret_access_key:
    secure: $AWS_SECRET
  region: "eu-central-1"  
  app: "telegram-alko"
  env: "telegram-alko-prod"
  bucket_name: "telegram-alko-bucket"