---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegram-alko
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegram-alko
  template:
    metadata:
      labels:
        app: telegram-alko
    spec:
      containers:
        - name: telegram-alko
          image: hugis420/telegram-alko:latest
          env:
            - name: ALKO_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: telegram-alko-secrets
                  key: ALKO_BOT_TOKEN
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: telegram-alko-secrets
                  key: SENTRY_DSN
            - name: ALKO_API_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: telegram-alko-secrets
                  key: ALKO_API_BASE_URL
            - name: ALKO_API_KEY
              valueFrom:
                secretKeyRef:
                  name: telegram-alko-secrets
                  key: ALKO_API_KEY
